// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GET",
    id: "48acbc40-3b04-11eb-92a9-b9893414db72",
    method: "GET",
    address:
      "http://127.0.0.1:8080/api/reviews/d797f860-5a95-11eb-8628-b9169fa055a3",
    headers: {
      Host: "test",
      "Content-Length": "0",
      Connection: "keep-alive",
      "Content-Type": "application/json"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
