// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "GET",
    id: "f0b18b39-e2af-4df9-9e07-0040cd44e4af",
    method: "GET",
    address:
      "http://52.157.230.55:8080/api/reviews/5d9d1cc0-3a7e-11eb-8a49-618ac10da998",
    headers: {
      Host: "test",
      "Content-Length": "0",
      Connection: "keep-alive",
      "Content-Type": "application/json"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
